name: Pre-commit


on:
  push:
    branches:
      - "*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  type-checks:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Setup pre-commit hooks
        run: |
          uv tool install pre-commit
          pre-commit install

      - name: Pre-commit
        run: pre-commit run --all-files
