name: Pytest


on:
  push:
    branches:
      - "*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  testing:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Test
        run: uv run pytest --no-header -v
