name: Pytest


on:
  push:
    branches:
      - "*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  testing:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@f98e06938123ccabd21905ea5d0069192241f9f1

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Test
        run: uv run pytest --no-header -v
